server:
  port: 8001

spring:
  application:
    name: cloud-payment-service  #服务名
  #zipkin 链路监控
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
        #采样率值介于 0 到 1 之间  1：表示全部采集
      probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver   #Mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: accp


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.jnf.springcloud.entities  #所有Entity别名类所在包

eureka:
  client:
    register-with-eureka: true  #表示是否将自己注册进Eureka Server 默认为 true
    fetch-registry: true  #是否从Eureka Server抓取已有的注册信息 默认为true 单节点无所谓 集群必须设置为true 才能配合ribbon使用负载均衡
    service-url:
      #defaultZone: http://localhost:7001/eureka   #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: payment8001  #修改Eureka服务名字
    prefer-ip-address: true  #访问路径可以显示IP地址
    #lease-renewal-interval-in-seconds: 1 #Eureka客户端向服务端发送心跳时间间隔,单位为秒(默认30秒)
    #lease-expiration-duration-in-seconds: 2 #Eureka服务端在收到最后一次心跳后等待时间上线,单位为秒(默认90秒)超市将剔出服务