server:
  port: 80

eureka:
  client:
    register-with-eureka: false  #表示是否将自己注册进Eureka Server 默认为 true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
feign:
  hystrix:
    enabled: true
